services:
  - type: web
    name: car-rental-api
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 15m
      - key: JWT_REFRESH_EXPIRATION
        value: 7d
      - key: APP_PORT
        value: 3000
      - key: MIDTRANS_SERVER_KEY
        value: SB-Mid-server-xxxxx
      - key: MIDTRANS_CLIENT_KEY
        value: SB-Mid-client-xxxxx
      - key: MIDTRANS_IS_PRODUCTION
        value: false
      - key: REDIS_HOST
        value: ""
      - key: REDIS_PORT
        value: "6379"
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: ""
